### PR TITLE
Bug fix and refine cloud training for DS2

### LINKED ISSUE #200: Bug fix and refine cloud training for DS2.
1. Add missing is_local argument (when set False, use pserver).
2. Add exception thrown if cloud cp failed.
3. Add cloud mkdir if cloud path for uploading does not exist.
4. Fix a bug using common path ./local_manifest for all nodes. (convert to /local_manifest)
5. Refine coding style.

### PR DESCRIPTION
**Pull request by xinghai-sun**
Resolve #200 

- Add missing is_local argument (when set False, use pserver).
- Add exception thrown if cloud cp failed.
- Add cloud mkdir if cloud path for uploading does not exist.
- Fix a bug using common path ./local_manifest for all nodes. (convert to /local_manifest)
- Refine coding style.

### CODE REVIEW

**Review by wanghaoshuang — APPROVED** [review]
LGTM.

File: deep_speech_2/cloud/pcloud_submit.sh [hunk 1]
```diff
@@ -1,17 +1,22 @@
...
+DEV_MANIFEST="../datasets/manifest.dev"
+VOCAB_FILE="../datasets/vocab/eng_vocab.txt"
+MEAN_STD_FILE="../mean_std.npz"
 # Configure output path in PaddleCloud filesystem
-CLOUD_DATA_DIR="/pfs/dlnel/home/demo/deepspeech2/data"
-CLOUD_MODEL_DIR="/pfs/dlnel/home/demo/deepspeech2/model"
+CLOUD_DATA_DIR="/pfs/dlnel/home/sunxinghai@baidu.com/deepspeech2/data"
+CLOUD_MODEL_DIR="/pfs/dlnel/home/sunxinghai@baidu.com/deepspeech2/model"
+# Configure cloud resources
+NUM_CPU=12
```
Comment (wanghaoshuang) [inline deep_speech_2/cloud/pcloud_submit.sh]: CPU和GPU应该设置一样，真实分配的GPU数量是来自`--cpu`，这是PaddleCloud的bug.
这里如果写成12，有可能会调度困难或报错。
